/**
 * Hosted first-deploy setup (idempotent), run by the Render pre-deploy step BEFORE migrations.
 * Connects as the platform's own database admin (ADMIN_DATABASE_URL) and makes sure the two roles the
 * architecture requires exist with the generated passwords (INV-1.4):
 *   mh_owner: owns the database and schema, runs migrations only.
 *   mh_app:   runtime role. Not superuser, no BYPASSRLS, owns nothing.
 * Passwords come from OWNER_PASSWORD / APP_PASSWORD (generated by the platform, never in the repository).
 */
import pg from "pg";
import { applyDerivedEnv } from "../src/lib/derive-env";

/** Replace the database name in a connection URL, keeping credentials and query string. */
function withDatabase(url: string, db: string): string {
  const u = new URL(url);
  u.pathname = `/${encodeURIComponent(db)}`;
  return u.toString();
}

export async function prepare(adminUrl: string, ownerPw: string, appPw: string, log: (m: string) => void = console.log, targetDb?: string) {
  if (ownerPw.length < 16 || appPw.length < 16) throw new Error("[PREP-002] OWNER_PASSWORD and APP_PASSWORD must be at least 16 characters");
  // Managed databases (RDS, Lightsail) start with only the maintenance database: create the application database first.
  if (targetDb && decodeURIComponent(new URL(adminUrl).pathname.slice(1)) !== targetDb) {
    const m = new pg.Client({ connectionString: adminUrl });
    await m.connect();
    try {
      const have = await m.query("SELECT 1 FROM pg_database WHERE datname = $1", [targetDb]);
      if (have.rows.length === 0) {
        await m.query(`CREATE DATABASE ${pg.escapeIdentifier(targetDb)} ENCODING 'UTF8' TEMPLATE template0`);
        log(`created database ${targetDb}`);
      }
    } catch (e) {
      throw new Error(`[PREP-006] cannot create database ${targetDb}: ${(e as Error).message}`);
    } finally {
      await m.end();
    }
    adminUrl = withDatabase(adminUrl, targetDb);
  }
  const c = new pg.Client({ connectionString: adminUrl });
  await c.connect();
  try {
    const q = async (sql: string, params: unknown[] = []) => (await c.query(sql, params)).rows;
    const lit = async (fmt: string, v: string) => ((await q("SELECT format($1, $2::text) AS s", [fmt, v]))[0] as { s: string }).s;
    const exists = async (r: string) => (await q("SELECT 1 FROM pg_roles WHERE rolname = $1", [r])).length > 0;

    const ownerSql = (await exists("mh_owner"))
      ? await lit("ALTER ROLE mh_owner WITH PASSWORD %L", ownerPw)
      : await lit("CREATE ROLE mh_owner LOGIN NOSUPERUSER NOBYPASSRLS PASSWORD %L", ownerPw);
    const appSql = (await exists("mh_app"))
      ? await lit("ALTER ROLE mh_app WITH PASSWORD %L", appPw)
      : await lit("CREATE ROLE mh_app LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE PASSWORD %L", appPw);
    try {
      await c.query(ownerSql);
      await c.query(appSql);
    } catch (e) {
      throw new Error(`[PREP-001] cannot create database roles with the platform admin user: ${(e as Error).message}`);
    }
    // Roles that already existed must not be privileged: refuse rather than run with them (INV-1.4, INV-8).
    const bad = await q("SELECT rolname FROM pg_roles WHERE rolname IN ('mh_owner','mh_app') AND (rolsuper OR rolbypassrls)");
    if (bad.length > 0) throw new Error("[PREP-004] an existing mh_owner/mh_app role is superuser or has BYPASSRLS; refusing to continue");
    const appPriv = await q("SELECT 1 FROM pg_roles WHERE rolname = 'mh_app' AND (rolcreatedb OR rolcreaterole)");
    if (appPriv.length > 0) throw new Error("[PREP-005] mh_app may create databases or roles; refusing to continue");
    // The admin must be able to hand ownership to mh_owner.
    await c.query("GRANT mh_owner TO CURRENT_USER").catch(() => undefined);
    const db = ((await q("SELECT current_database() AS d"))[0] as { d: string }).d;
    await c.query(`ALTER DATABASE ${pg.escapeIdentifier(db)} OWNER TO mh_owner`);
    await c.query("ALTER SCHEMA public OWNER TO mh_owner");
    // Runtime role may connect; everything else is granted table by table by the migrations.
    await c.query(`GRANT CONNECT ON DATABASE ${pg.escapeIdentifier(db)} TO mh_app`);
    log("database roles ready (mh_owner, mh_app)");
  } finally {
    await c.end();
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  applyDerivedEnv();
  const { ADMIN_DATABASE_URL, OWNER_PASSWORD, APP_PASSWORD, DB_NAME } = process.env;
  if (!ADMIN_DATABASE_URL || !OWNER_PASSWORD || !APP_PASSWORD) {
    console.error("[PREP-003] ADMIN_DATABASE_URL, OWNER_PASSWORD and APP_PASSWORD are required");
    process.exit(1);
  }
  prepare(ADMIN_DATABASE_URL, OWNER_PASSWORD, APP_PASSWORD, console.log, DB_NAME).catch((e) => {
    console.error(e.message);
    process.exit(1);
  });
}
